onetimerainbow=0; //Manicorn gets rainbow-powered
player=1;
turnspeed=10;
maxspeed=9;
accel=1.4;
lookdir=0;
hp=100;
maxhp=100;
invincible=0; //Prevent further hits
shotcyc=8;
ignoreall=1;
spreadshot=0;
crazyshot=0; //yes, they should be controlled by the same variable. get off my lawn
homingshot=0; //again, this should be the same as above in proper programming...
exploshot=0; //this is getting crazy
aicyc=0;
aicontrol1=0;
aicontrol2=0;
lasercyc=0;
